schema_version: "2.0"
description: "Feigenbaum-Möbius constant integration and validation"
semantic_scope: "implementation"
proficiency_level: "research"
estimated_context_weight: 0.6
validation_type: "automated"

files:
  - "[README.md]": "POC hypothesis, design, validation results"
