schema_version: "2.0"
description: "PAC-Lazy Hierarchical Field substrate POC"
semantic_scope: "implementation"
proficiency_level: "research"
estimated_context_weight: 0.8
validation_type: "automated"

files:
  - "[README.md]": "POC hypothesis, design, success criteria"

child_directories:
  - name: "journals"
    description: "Daily research logs"
  - name: "scripts"
    description: "Experiment scripts (exp_NN_name.py)"
  - name: "results"
    description: "JSON experiment outputs"
