schema_version: "2.0"
description: "Premass phase dynamics via MAS equation"
semantic_scope: "research"
proficiency_level: "experimental"
estimated_context_weight: 0.7
validation_type: "manual"

files:
  - "[README.md]": "POC hypothesis, MAS equation, preliminary results"
