schema_version: "2.0"
description: "Journal entries for POC-004 stellar formation experiments"
semantic_scope: "documentation"
proficiency_level: "research"

files:
  - "[2026-01-08_jeans_testing.md]": "Initial Jeans collapse testing"
